#!/bin/bash

cd /data

filepath=`ls whole/*.vcf`
filename="${filepath##*/}"
rootname=${filename::-4}

echo 'creating ingroups for introgression detection'

cd ./output

python3 \
/opt/Introgression-detection/src/main.py \
create_ingroup \
-ind=$rootname \
-vcf=/data/\*.bcf \
-weights=/opt/precomputed-files/strick_callability_mask_hg38.bed \
-outgroup=/opt/precomputed-files/Outgroup_1000g_HGDP_hg38.txt \
-ancestral=/opt/hg38-ancestral/\*.fa \
-out=obs

cd ..
